image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2388.13033,    0.     ,  721.91935,
            0.     , 2383.59661,  507.25566,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.044949, 0.131803, -0.003156, -0.000776, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2380.90015,    0.     ,  720.82899,    0.     ,
            0.     , 2376.04834 ,  505.51420,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
